name: Docker Image Front  # Nom du workflow visible dans l'interface GitHub Actions

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]  

jobs:
  docker_frontend:
    runs-on: ubuntu-latest  # Exécute ce job sur une machine virtuelle Ubuntu

    steps:
      # Étape 1 : Téléchargement des sources du dépôt
      - name: Checkout
        uses: actions/checkout@v4  # Utilise l'action GitHub pour cloner le dépôt

      # Étape 2 : Configuration de QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # Installe QEMU pour supporter les architectures x86 et ARM

      # Étape 3 : Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Configure Docker Buildx pour les images multi-architectures

      # Étape 4 : Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      # Étape 5 : Construction et push de l'image Docker sur Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./front  # Chemin du répertoire contenant les sources à construire
          file: front/Dockerfile  # Chemin vers le Dockerfile pour la construction de l'image
          push: true  # Pousse l'image sur Docker Hub après la construction
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest  # Tag pour l'image Docker (user/image:tag)
