
name: SonarCloud Front  # Nom du workflow pour l'analyse SonarCloud du frontend
on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ] 
jobs:
  sonar_frontend:
    name: Build and analyze frontend  # Nom du job d'analyse du frontend
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu
    defaults:
      run:
        # Définit le répertoire de travail comme étant le dossier 'front'
        working-directory: front
    steps:
      # Étape 1 : Télécharger le code source du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3
      # Étape 2 : Configurer Node.js version 16 pour le projet
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"  # Version de Node.js requise pour le projet
          cwd: "front"  # Répertoire de travail pour cette action
      # Étape 3 : Installer les dépendances Node.js du frontend
      - name: Install dependencies
        run: npm install  # Installe les dépendances définies dans package.json
      # Étape 4 : Lancer l'analyse SonarCloud sur le frontend
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front  # Spécifie le dossier racine du projet frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Jeton GitHub pour authentification
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Jeton SonarCloud pour authentification
