name: Tests and Code Coverage Back

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 

jobs:
  build_backend:
    runs-on: ubuntu-latest  # Spécifie que le job s'exécutera sur une machine virtuelle Ubuntu

    steps:
      # Étape 1 : Afficher un message pour indiquer le lancement des tests Maven pour le backend
      - run: echo "Launching Mvn Test on Backend source code"

      # Étape 2 : Cloner le dépôt avec l'action checkout (permet d'accéder au code source du repository)
      - uses: actions/checkout@v3

      # Étape 3 : Configurer JDK 11 pour le projet Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Utilisation de la version 11 de Java
          distribution: 'temurin'  # Distribution AdoptOpenJDK (Temurin)
          cache: maven  # Mise en cache des dépendances Maven pour accélérer les builds futurs
      
      # Étape 4 : Construction et exécution des tests Maven
      - name: Build with Maven
        working-directory: ${{ github.workspace }}/back  # Spécifie le répertoire backend pour la construction
        run: mvn clean test --file pom.xml  # Exécute les tests Maven et génère les rapports de couverture
      
      # Étape 5 : Vérification du rapport JaCoCo pour s'assurer que la couverture de code a été générée
      - name: Check JaCoCo Report
        run: cat ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml  # Affiche le rapport JaCoCo pour la couverture des tests
      
      # Étape 6 : Ajouter le rapport de couverture JaCoCo à la plateforme GitHub (par exemple, pour afficher dans les PRs)
      - name: Add coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1  # Utilisation d'un action GitHub pour télécharger et afficher les rapports JaCoCo
        with:
          paths: |
            ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml  # Chemin vers le rapport JaCoCo
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token GitHub pour authentifier l'action
          title: Code Coverage  # Titre de l'affichage du rapport de couverture
          min-coverage-overall: 80  # Définir un seuil de couverture globale à 80%
          min-coverage-changed-files: 80  # Définir un seuil de couverture pour les fichiers modifiés à 80%
          pass-emoji: 🍏  # Emoji pour indiquer un test réussi (vert)
          fail-emoji: ❌  # Emoji pour indiquer un test échoué (rouge)
          debug-mode: false  # Désactivation du mode débogage pour un affichage normal des résultats
      
      # Étape 7 : Affichage de la couverture globale
      - run: echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"  # Affiche la couverture totale après les tests

      # Étape 8 : Affichage de la couverture des fichiers modifiés
      - run: echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"  # Affiche la couverture des fichiers modifiés uniquement

      # Étape 9 : Commit du rapport de couverture dans le dépôt, pour qu'il soit visible sur GitHub
      - name: Commit Jacoco Code Coverage Report
        run: |
          # Configure l'identité Git pour l'utilisateur qui fait le commit
          git config --global user.email "benyahia.zaim@gmail.com"
          git config --global user.name "zcbe"
          
          # Récupère les dernières modifications du dépôt pour éviter les conflits
          git fetch
          git checkout main  # Bascule sur la branche "main"
          git pull origin main  # Récupère les dernières modifications depuis le dépôt distant
          
          # Ajoute les fichiers de couverture générés à Git
          git add -f back/target/site/jacoco  # Force l'ajout du répertoire JaCoCo (sinon il peut être ignoré par .gitignore)
          
          # Commit le rapport de couverture avec un message spécifique
          git commit -m "Add Jacoco code coverage report"
          
          # Pousse le commit vers la branche "main" du dépôt distant
          git push origin main  # Pousse le rapport sur GitHub pour qu'il soit visible
