name: Tests and Code Coverage Front  

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'coverage/bobapp/**'  # Ignore les changements dans le dossier de couverture pour éviter les boucles
  pull_request:
    branches: [ "main" ]  

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front 

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Étape 1 : Récupération du code source du dépôt
      - uses: actions/checkout@v3

      # Étape 2 : Configuration de la version de Node.js spécifiée dans le matrix
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Étape 3 : Installation des dépendances Node.js
      - name: Install dependencies
        run: npm install

      # Étape 4 : Exécution des tests avec génération de la couverture du code
      - name: Test coverage
        run: npm run test-coverage

      # Étape 5 : Vérifier le rapport de couverture
      - name: Check Coverage Report
        run: cat coverage/bobapp/index.html
        
      # Étape 6 : Vérifie les fichiers modifiés
      - name: Check modified files
        run: git status

      # Étape 7 : Commit et push conditionnel du rapport de couverture
      - name: Commit and Push Karma Code Coverage Report
        if: github.ref == 'refs/heads/main'
        env:
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}  # Utilisez un secret GitHub pour sécuriser le jeton d'accès
        run: |
          # Configuration de l'identité Git pour le commit
          git config --global user.email "benyahia.zaim@gmail.com"
          git config --global user.name "zcbe"
          
          # Synchronisation avec la branche "main" pour éviter les conflits
          git fetch
          git checkout main
          git pull origin main
          
          # Forcer l'ajout du rapport de couverture dans le répertoire "coverage/bobapp"
          git add -f coverage/bobapp
          
          # Vérifie s'il y a des modifications à committer
          if ! git diff-index --quiet HEAD; then
            # Création d'un commit pour le rapport de couverture de code
            git commit -m "Add Karma code coverage report"
            # Poussée du commit vers la branche "main" sur le dépôt
            git push https://$PUSH_TOKEN@github.com/zcbe/Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD.git main
          else
            echo "Aucun changement à pousser."
          fi

      # Étape 8 : Affiche le statut des tests avec une icône
      - run: echo "🍏 Npm run test-coverage's status is ${{ job.status }}."
 