name: Tests and Code Coverage Back
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back # Définit 'back' comme répertoire de travail

    steps:
      - run: echo "Launching Mvn Test on Backend source code"
      
      # Récupération du code source
      - uses: actions/checkout@v3

      # Configuration de JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      # Lancer les tests avec Maven
      - name: Build with Maven
        run: mvn clean test
      
      # Affiche le statut des tests
      - run: echo "🍏 Mvn Test's status is ${{ job.status }}."

      # Génération de la couverture de code Jacoco
      - name: Add coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          pass-emoji: 🍏
          fail-emoji: ❌
          debug-mode: false

      # Affiche le taux de couverture global et des fichiers modifiés
      - run: echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
      - run: echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      # Ajout du rapport de couverture de code dans le dépôt
      - name: Commit Code Coverage Report
        run: |
          git config --global user.email "benyahia.zaim@gmail.com"
          git config --global user.name "zcbe"
          
          # Vérifie si des fichiers ont changé avant de committer
          if ! git diff --quiet; then
            git add target/site/jacoco # Ajoute uniquement les rapports générés
            git commit -m "Add Jacoco code coverage report"
            git push origin dev
          else
            echo "No changes to commit"
          fi
